runtime: python311 
instance_class: F2 

entrypoint: gunicorn -b :$PORT app:app  # Gunicorn is used as the HTTP server

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  
env_variables:
  GAE_ENV: standard

runtime_config:
  python_version: 3
